version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: fork-ts-checker-webpack-plugin
    versions:
    - 6.2.4
  - dependency-name: typescript
    versions:
    - 4.2.3
