version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: fork-ts-checker-webpack-plugin
    versions:
    - 6.1.0
    - 6.1.1
    - 6.2.0
    - 6.2.1
    - 6.2.4
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: eslint
    versions:
    - 7.19.0
    - 7.21.0
